name: build

on:
  workflow_dispatch:

jobs:
  make-wheels:
    name: Build wheels ${{ matrix.os }} ${{ matrix.cibw_arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-14", "ubuntu-latest", "windows-latest"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: "Build wheels"
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_ARCHS: native
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: pp*
          CIBW_BUILD_FRONTEND: build

      - name: "Upload wheel as artifact"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}-${{ matrix.cibw_arch }}-wheel
          path: "wheelhouse/*.whl"
